# Generated by Django 5.2.17 on 2026-09-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prep_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='protocols.prepstep')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='procedures.procedure')),
            ],
        ),
    ]
