# Generated by Django 5.2.17 on 2026-08-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrepProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrepStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('minutes_before_procedure', models.PositiveIntegerField()),
                ('requires_confirmation', models.BooleanField(default=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='protocols.prepprotocol')),
            ],
            options={
                'ordering': ['-minutes_before_procedure', 'order'],
            },
        ),
    ]
