# Generated by Django 5.2.17 on 2026-08-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('prep_in_progress', 'Prep In Progress'), ('ready', 'Ready'), ('attention_needed', 'Attention Needed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='patients.patient')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='protocols.prepprotocol')),
            ],
        ),
    ]
